baseURL = 'https://www.oxborrow.net/'
languageCode = 'en-gb'
title = 'oxborrow.net'

[params]
  AuthorName = 'Toby Oxborrow'

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
