baseURL = 'https://www.oxborrow.net/'
languageCode = 'en-gb'
title = 'oxborrow.net'

[permalinks]
  [permalinks.page]
    blog = '/blog/:year/:month/:slug/'

[build]
  [build.buildStats]
    enable = true

[params]
    AuthorName = 'Toby Oxborrow'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
[[menu.main]]
    name = 'Tech'
    pageRef = '/tech'
    weight = 2
[[menu.main]]
    name = 'Pics'
    pageRef = '/pics'
    weight = 3
[[menu.main]]
    name = 'Grim Dark'
    pageRef = '/grimdark'
    weight = 4
[[menu.main]]
    name = 'Links'
    url = 'https://pinboard.in/u:tobyoxborrow/'
    weight = 91
	[menu.main.params]
		class = 'remote'
[[menu.main]]
    name = 'Social'
    url = 'https://infosec.exchange/@kanzenmaster'
    weight = 92
	[menu.main.params]
        rel = 'me'
		class = 'remote'
[[menu.main]]
    name = 'Career'
    url = 'https://www.linkedin.com/in/tobyoxborrow/'
    weight = 93
	[menu.main.params]
		class = 'remote'
